/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinanzanavideña.vistas;

import adivinanzanavideña.logica.Controlador;
import javax.swing.JOptionPane;

public class FrameNavidad extends javax.swing.JFrame {

    Controlador control = new Controlador();
    String emoji;
    String matriz[][] = new String[4][4];
    int cantEncontrados;

    public FrameNavidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReiniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jtfResultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfEncontrados = new javax.swing.JTextField();
        jtfCant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfElegido = new javax.swing.JTextField();
        btnLentes = new javax.swing.JButton();
        btnEstrella = new javax.swing.JButton();
        btnRisa = new javax.swing.JButton();
        btnCorazon = new javax.swing.JButton();
        jtfCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReiniciar.setText("reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Segoe UI Emoji", 0, 48)); // NOI18N
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jtfResultado.setEditable(false);

        jLabel7.setText("Resultado:");

        jLabel6.setText("Encontrados:");

        jtfEncontrados.setEditable(false);

        jtfCant.setEditable(false);
        jtfCant.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N

        jLabel5.setText("Cantidad:");

        jLabel4.setText("Elegido:");

        jtfElegido.setEditable(false);
        jtfElegido.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jtfElegido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfElegidoActionPerformed(evt);
            }
        });

        btnLentes.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnLentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinanzanavideña/imagenes/lentes.png"))); // NOI18N
        btnLentes.setMaximumSize(new java.awt.Dimension(100, 100));
        btnLentes.setMinimumSize(new java.awt.Dimension(100, 100));
        btnLentes.setPreferredSize(new java.awt.Dimension(100, 100));
        btnLentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLentesActionPerformed(evt);
            }
        });

        btnEstrella.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinanzanavideña/imagenes/estrella.png"))); // NOI18N
        btnEstrella.setMaximumSize(new java.awt.Dimension(100, 100));
        btnEstrella.setMinimumSize(new java.awt.Dimension(100, 100));
        btnEstrella.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEstrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstrellaActionPerformed(evt);
            }
        });

        btnRisa.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnRisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinanzanavideña/imagenes/risa.png"))); // NOI18N
        btnRisa.setMaximumSize(new java.awt.Dimension(100, 100));
        btnRisa.setMinimumSize(new java.awt.Dimension(100, 100));
        btnRisa.setPreferredSize(new java.awt.Dimension(100, 100));
        btnRisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRisaActionPerformed(evt);
            }
        });

        btnCorazon.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnCorazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinanzanavideña/imagenes/corazon.png"))); // NOI18N
        btnCorazon.setMaximumSize(new java.awt.Dimension(100, 100));
        btnCorazon.setMinimumSize(new java.awt.Dimension(100, 100));
        btnCorazon.setPreferredSize(new java.awt.Dimension(100, 100));
        btnCorazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorazonActionPerformed(evt);
            }
        });

        jLabel3.setText("elija su personaje");

        jLabel2.setText("ingrese la cantidad de veces que cree que aparece el personaje");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("ADIVINANZA NAVIDEÑA!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCorazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLentes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3))
                                    .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfCant)
                            .addComponent(jtfEncontrados, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfElegido, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(232, 232, 232))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(btnReiniciar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLentes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfElegido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfElegidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfElegidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfElegidoActionPerformed

    private void btnLentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLentesActionPerformed
        emoji = "😂";
        jTextArea.setText("");
        ejecucion(emoji);

    }//GEN-LAST:event_btnLentesActionPerformed

    private void btnEstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstrellaActionPerformed
        emoji = "🤩";
        jTextArea.setText("");
        ejecucion(emoji);
    }//GEN-LAST:event_btnEstrellaActionPerformed

    private void btnRisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRisaActionPerformed
        emoji = "😂";
        jTextArea.setText("");
        ejecucion(emoji);
    }//GEN-LAST:event_btnRisaActionPerformed

    private void btnCorazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorazonActionPerformed
        emoji = "😍";
        jTextArea.setText("");
        ejecucion(emoji);
    }//GEN-LAST:event_btnCorazonActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnReiniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorazon;
    private javax.swing.JButton btnEstrella;
    private javax.swing.JButton btnLentes;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jtfCant;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfElegido;
    private javax.swing.JTextField jtfEncontrados;
    private javax.swing.JTextField jtfResultado;
    // End of variables declaration//GEN-END:variables

    private void ejecucion(String emoji) {
        try {
            int cantidad = Integer.parseInt(jtfCantidad.getText());

            if (cantidad >= 0 && cantidad <= 16) {
                matriz = control.generarMatriz();
                cantEncontrados = control.determinarCantidadEmoji(emoji, cantidad, matriz);

                jtfEncontrados.setText(String.valueOf(cantEncontrados));
                jtfElegido.setText(emoji);
                jtfCant.setText(String.valueOf(cantidad));

                if (cantEncontrados == cantidad) {
                    jtfResultado.setText("ACERTO!");
                } else {
                    jtfResultado.setText("FALLO!");
                }
                dibujarMatriz(matriz);
            } else {
                JOptionPane.showMessageDialog(null, "ingrese un numero del 1 al 16");
                limpiarCampos();
            }
        } catch (NullPointerException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ingrese un numero valido");
        }
    }

    private void limpiarCampos() {
        jtfCant.setText("");
        jtfCantidad.setText("");
        jtfElegido.setText("");
        jtfEncontrados.setText("");
        jtfResultado.setText("");
        jTextArea.setText("");

    }

    private void dibujarMatriz(String matriz[][]) {
        for (int f = 0; f < 4; f++) {
            for (int c = 0; c < 4; c++) {

                jTextArea.setText(jTextArea.getText() + matriz[f][c] + " ");

            }
            jTextArea.setText(jTextArea.getText() + "\n");
        }
    }
}
